### ISSUE TITLE
Добавить проверку параметров в начало функции

### ISSUE THREAD

**Issue by in19farkt** [rlkvrv/vault#18]
Возможно стоит добаить пару проверок, при выполнении которых нужно просто скипнуть (не ревертнуть) вызов:
- если `loss == 0`
- если `strategies[_strategy].lastReport == 0`. добавленная стратегия будет иметь в lastReport ноль, до первого репорта

https://github.com/rlkvrv/vault/blob/5572bd34901ab2b532ad7c5e2bf17ce65e27e9ba/contracts/Vault.sol#L411-L412

**Comment by rlkvrv** [comment]
- ты возможно имел в виду `gain == 0`, если так, то при этом условии `_assessFees` не будет вызвана
- опять же до первого репорта `gain` будет равен нулю, поэтому `_assessFees` не вызовется и есть ли смысл проверять `lastReport` на ноль?

**Comment by in19farkt** [comment]
@rlkvrv да, я об этом тоже думал, но с другой стороны это зависит от того как конкретная стратегия в первый раз вызовет report, волт ничего не знает о том, как функция report будет использоваться стратегиями, и я считаю что волт должен этот момент контролировать
